//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hall_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commands
    {
        public int CommandID { get; set; }
        public int EquipmentID { get; set; }
        public string CommandName { get; set; }
        public string CommandText { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
