//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hall_management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class Hall_mngmt01Entities : DbContext
    {
        public Hall_mngmt01Entities()
            : base("name=Hall_mngmt01Entities")
        {
        }
        public bool AuthenticateUser(string username, string password)
        {
            // Проверка наличия пользователя в базе данных
            var user = Users.FirstOrDefault(u => u.Username == username);

            // Если пользователь не найден, возвращаем false
            if (user == null)
                return false;

            // Проверка правильности пароля
            return user.Password == password;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        

        public virtual DbSet<Commands> Commands { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<EquipmentCommandsView> EquipmentCommandsView { get; set; }
    }
}
